version: '2'
services:

 nginx:
  #
  # nginx
  # =========
  #
  # This service can be used as a reverse proxy for an API node
  # 
  build: nginx-dir/
  ports:
   - "0.0.0.0:443:8080"

 seed:
  #
  # Seed Node
  # =========
  #
  # This service can be used to deploy a seed node that exposes the P2P
  # port to the internet at port 6666 (change below)
  #
  image: peerplays-network:test-1.4.5
  environment:
   - 'PEERPLAYSD_P2P_ENDPOINT=0.0.0.0:6666'
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  ports:
   - "0.0.0.0:6666:6666"
  volumes:
   - "./seed:/var/lib/peerplays"

 node:
  #
  # Node
  # ====
  #
  # This service can be used to deploy a full node that exposes the RPC
  # port to the internet at port 8090 (change below)
  #
  image: peerplays-network:test-1.4.5
  depends_on:
   - seed
  ports:
   - "0.0.0.0:8090:8090"
  environment:
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
   - 'PEERPLAYSD_RPC_ENDPOINT=0.0.0.0:8090'
  volumes:
  - "./node:/var/lib/peerplays"

 witness:
  #
  # Witness Node
  # =========
  #
  # This service can be used to deploy a block producer.
  #
  # NOTE:
  # Please change the private key and witness id accordingly!!
  #
  image: peerplays-network:test-1.4.5
  depends_on:
   - seed
  environment:
   - 'PEERPLAYSD_PRIVATE_KEY=["TEST...","5..."]'
   - 'PEERPLAYSD_WITNESS_ID="1.6.x"'
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  volumes:
  - "./witness:/var/lib/peerplays"
